// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CollectionDataOptions {
    /**
     * Creates a new CollectionDataOptions instance.
     * @param {Partial<CollectionDataOptions>} [$$source = {}] - The source object to create the CollectionDataOptions.
     */
    constructor($$source = {}) {
        if (!("pureName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pureName"] = "";
        }
        if (!("countDocuments" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["countDocuments"] = false;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("skip" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skip"] = 0;
        }
        if (!("aggregate" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["aggregate"] = null;
        }
        if (!("condition" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["condition"] = {};
        }
        if (!("sort" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["sort"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectionDataOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectionDataOptions}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("condition" in $$parsedSource) {
            $$parsedSource["condition"] = $$createField5_0($$parsedSource["condition"]);
        }
        if ("sort" in $$parsedSource) {
            $$parsedSource["sort"] = $$createField6_0($$parsedSource["sort"]);
        }
        return new CollectionDataOptions(/** @type {Partial<CollectionDataOptions>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
