// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serializer$0 from "../pkg/serializer/models.js";

/**
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function GetSettings() {
    return $Call.ByID(121239849).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = serializer$0.Response.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
