// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serializer$0 from "../pkg/serializer/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {{ [_ in string]?: string }} connection
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Delete(connection) {
    return $Call.ByID(4017934084, connection).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.GetConnectionsRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Get(req) {
    return $Call.ByID(1967118881, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function List() {
    return $Call.ByID(4190849215).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {{ [_ in string]?: string }} connection
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Save(connection) {
    return $Call.ByID(982060386, connection).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {{ [_ in string]?: any }} connection
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Test(connection) {
    return $Call.ByID(2587498627, connection).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = serializer$0.Response.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
