// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serializer$0 from "../pkg/serializer/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.CollectionDataRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function CollectionData(req) {
    return $Call.ByID(2117279583, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.CreateTableRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function CreateTable(req) {
    return $Call.ByID(2355414609, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.DatabaseRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Disconnect(req) {
    return $Call.ByID(1184787293, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.DatabaseRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Ping(req) {
    return $Call.ByID(789967547, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.DatabaseKeepOpenRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Refresh(req) {
    return $Call.ByID(2824777594, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.DatabaseRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function ServerVersion(req) {
    return $Call.ByID(1182222400, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.SqlSelectRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function SqlSelect(req) {
    return $Call.ByID(173605353, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.DatabaseRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Status(req) {
    return $Call.ByID(1769750465, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.DatabaseRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Structure(req) {
    return $Call.ByID(1888086940, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.DatabaseRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function SyncModel(req) {
    return $Call.ByID(2070305789, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = serializer$0.Response.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
