// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modules$0 from "../db/standard/modules/models.js";

export class CollectionDataRequest {
    /**
     * Creates a new CollectionDataRequest instance.
     * @param {Partial<CollectionDataRequest>} [$$source = {}] - The source object to create the CollectionDataRequest.
     */
    constructor($$source = {}) {
        if (!("conid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conid"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("Options" in $$source)) {
            /**
             * @member
             * @type {modules$0.CollectionDataOptions | null}
             */
            this["Options"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectionDataRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectionDataRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Options" in $$parsedSource) {
            $$parsedSource["Options"] = $$createField2_0($$parsedSource["Options"]);
        }
        return new CollectionDataRequest(/** @type {Partial<CollectionDataRequest>} */($$parsedSource));
    }
}

export class CreateDatabaseRequest {
    /**
     * Creates a new CreateDatabaseRequest instance.
     * @param {Partial<CreateDatabaseRequest>} [$$source = {}] - The source object to create the CreateDatabaseRequest.
     */
    constructor($$source = {}) {
        if (!("conid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conid"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateDatabaseRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateDatabaseRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateDatabaseRequest(/** @type {Partial<CreateDatabaseRequest>} */($$parsedSource));
    }
}

export class CreateTableRequest {
    /**
     * Creates a new CreateTableRequest instance.
     * @param {Partial<CreateTableRequest>} [$$source = {}] - The source object to create the CreateTableRequest.
     */
    constructor($$source = {}) {
        if (!("conid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conid"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("tableName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tableName"] = "";
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTableRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateTableRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField3_0($$parsedSource["columns"]);
        }
        return new CreateTableRequest(/** @type {Partial<CreateTableRequest>} */($$parsedSource));
    }
}

export class DatabaseKeepOpenRequest {
    /**
     * Creates a new DatabaseKeepOpenRequest instance.
     * @param {Partial<DatabaseKeepOpenRequest>} [$$source = {}] - The source object to create the DatabaseKeepOpenRequest.
     */
    constructor($$source = {}) {
        if (!("conid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conid"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("keepOpen" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keepOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseKeepOpenRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DatabaseKeepOpenRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseKeepOpenRequest(/** @type {Partial<DatabaseKeepOpenRequest>} */($$parsedSource));
    }
}

export class DatabaseRequest {
    /**
     * Creates a new DatabaseRequest instance.
     * @param {Partial<DatabaseRequest>} [$$source = {}] - The source object to create the DatabaseRequest.
     */
    constructor($$source = {}) {
        if (!("conid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conid"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DatabaseRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseRequest(/** @type {Partial<DatabaseRequest>} */($$parsedSource));
    }
}

export class GetConnectionsRequest {
    /**
     * Creates a new GetConnectionsRequest instance.
     * @param {Partial<GetConnectionsRequest>} [$$source = {}] - The source object to create the GetConnectionsRequest.
     */
    constructor($$source = {}) {
        if (!("conid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetConnectionsRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetConnectionsRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetConnectionsRequest(/** @type {Partial<GetConnectionsRequest>} */($$parsedSource));
    }
}

export class ScriptRequest {
    /**
     * Creates a new ScriptRequest instance.
     * @param {Partial<ScriptRequest>} [$$source = {}] - The source object to create the ScriptRequest.
     */
    constructor($$source = {}) {
        if (!("packageName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["packageName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptRequest(/** @type {Partial<ScriptRequest>} */($$parsedSource));
    }
}

export class ServerPingRequest {
    /**
     * Creates a new ServerPingRequest instance.
     * @param {Partial<ServerPingRequest>} [$$source = {}] - The source object to create the ServerPingRequest.
     */
    constructor($$source = {}) {
        if (!("connections" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["connections"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerPingRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerPingRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connections" in $$parsedSource) {
            $$parsedSource["connections"] = $$createField0_0($$parsedSource["connections"]);
        }
        return new ServerPingRequest(/** @type {Partial<ServerPingRequest>} */($$parsedSource));
    }
}

export class ServerRefreshRequest {
    /**
     * Creates a new ServerRefreshRequest instance.
     * @param {Partial<ServerRefreshRequest>} [$$source = {}] - The source object to create the ServerRefreshRequest.
     */
    constructor($$source = {}) {
        if (!("conid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conid"] = "";
        }
        if (!("keepOpen" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keepOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerRefreshRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerRefreshRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerRefreshRequest(/** @type {Partial<ServerRefreshRequest>} */($$parsedSource));
    }
}

export class SqlSelectRequest {
    /**
     * Creates a new SqlSelectRequest instance.
     * @param {Partial<SqlSelectRequest>} [$$source = {}] - The source object to create the SqlSelectRequest.
     */
    constructor($$source = {}) {
        if (!("conid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["conid"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("Select" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["Select"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SqlSelectRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SqlSelectRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SqlSelectRequest(/** @type {Partial<SqlSelectRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = modules$0.CollectionDataOptions.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
