// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serializer$0 from "../pkg/serializer/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} conid
 * @param {boolean} kill
 * @returns {$CancellablePromise<void>}
 */
export function Close(conid, kill) {
    return $Call.ByID(4114713739, conid, kill);
}

/**
 * @param {$models.CreateDatabaseRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function CreateDatabase(req) {
    return $Call.ByID(2233009896, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {{ [_ in string]?: string }} request
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function ListDatabases(request) {
    return $Call.ByID(1967341381, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.ServerPingRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Ping(req) {
    return $Call.ByID(1315757121, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.ServerRefreshRequest | null} req
 * @returns {$CancellablePromise<serializer$0.Response | null>}
 */
export function Refresh(req) {
    return $Call.ByID(2955217196, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<any>}
 */
export function ServerStatus() {
    return $Call.ByID(1784323316);
}

// Private type creation functions
const $$createType0 = serializer$0.Response.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
